/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CliptoTokenStorage,
  CliptoTokenStorageInterface,
} from "../CliptoTokenStorage";

const _abi = [
  {
    inputs: [],
    name: "minter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CliptoTokenStorage__factory {
  static readonly abi = _abi;
  static createInterface(): CliptoTokenStorageInterface {
    return new utils.Interface(_abi) as CliptoTokenStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CliptoTokenStorage {
    return new Contract(address, _abi, signerOrProvider) as CliptoTokenStorage;
  }
}
